### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por ID
GET http://localhost:1234/movies/3709a00b-5fc6-11

### Recuperar todas las peliculas por un genero
GET  http://localhost:1234/movies?genre=ACTION

### Crear una pelicula
POST  http://localhost:1234/movies
Content-Type: application/json

{
    "title" : "ET",
    "year" : 1984,
    "director" : "Stephen Spilberg",
    "duration" : 112,
    "poster" : "https://flxt.tmsimg.com/assets/p10998_p_v8_ao.jpg",
    "genre": [
        "Drama"   

    ]
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/9a6dsa

### Actualizar una pelicula
PATCH  http://localhost:1234/movies/3709a00b-5fc6-11
Content-Type: application/json

{
    
    "year" : 2000
}
